project:
  type: website
  output-dir: docs   # all rendered files go here

website:
  title: "Paloma Zarazua"
  navbar:
    logo: images/neutrophil.PNG   
    left:
      - href: index.qmd
        text: Home
      - href: background.qmd
        text: Background
      - href: Research.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: www/custom.css  # your custom CSS file
