project:
  type: website

website:
  title: "Paloma Zarazua"
  navbar:
    logo: images/neutrophil.PNG   # ðŸ‘ˆ move it here
    left:
      - href: index.qmd
        text: Home
      - href: background.qmd
        text: Background
      - href: Research.qmd
        text: Research


format:

  html:
    theme: cosmo
    css: www/custom.css

output-dir: docs